"""Spine interface contracts for LIMA Guardian.

Interfaces only: no runtime implementation is provided in PR 4A.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from lima_guardian.spine_models import SpineDashboardSnapshot, SpineEventEnvelope, SpineProducer, SpineProject, SpineRelation, SpineTask


@runtime_checkable
class SpineStore(Protocol):
    def init_schema(self) -> None: ...

    def get_event(self, event_id: str) -> SpineEventEnvelope | None: ...
    def get_task(self, task_id: str) -> SpineTask | None: ...
    def list_tasks(self, *, room_id: str | None = None, project_id: str | None = None, status: str | None = None, limit: int = 100) -> list[SpineTask]: ...
    def upsert_task(self, task: SpineTask) -> SpineTask: ...

    def get_project(self, project_id: str) -> SpineProject | None: ...
    def list_projects(self, *, room_id: str | None = None, limit: int = 100) -> list[SpineProject]: ...
    def upsert_project(self, project: SpineProject) -> SpineProject: ...

    def append_event(self, event: SpineEventEnvelope) -> SpineEventEnvelope: ...
    def list_events(self, *, room_id: str | None = None, task_id: str | None = None, project_id: str | None = None, subsystem: str | None = None, limit: int = 100) -> list[SpineEventEnvelope]: ...

    def record_relation(self, relation: SpineRelation) -> SpineRelation: ...
    def list_relations(self, *, from_entity_id: str | None = None, to_entity_id: str | None = None, relation_type: str | None = None, limit: int = 200) -> list[SpineRelation]: ...
    def register_producer(self, producer: SpineProducer) -> SpineProducer: ...
    def list_producers(self) -> list[SpineProducer]: ...
    def get_dashboard_snapshot(self, *, room_id: str | None = None, limit: int = 20) -> SpineDashboardSnapshot: ...


@runtime_checkable
class SpineEventBus(Protocol):
    def register_producer(self, producer: SpineProducer) -> SpineProducer: ...
    def list_producers(self) -> list[SpineProducer]: ...
    def ingest(self, event: SpineEventEnvelope) -> dict[str, Any]: ...


@runtime_checkable
class TaskAdapter(Protocol):
    def sync_chat_task_created(self, *, task: Any, session: Any) -> str | None: ...
    def sync_chat_task_status(self, *, task: Any, status: str, session: Any) -> str | None: ...
    def emit_task_master_action(self, *, task: Any, action: str, actor_id: str, summary: str | None = None, payload: dict[str, Any] | None = None, session: Any | None = None) -> dict[str, Any]: ...
    def get_task_by_chat_task_id(self, *, chat_task_id: str) -> SpineTask | None: ...


@runtime_checkable
class ProjectAdapter(Protocol):
    def create_project(self, *, project: SpineProject, actor_id: str | None = None, source_ref: str | None = None, session: Any | None = None) -> SpineProject: ...
    def update_metadata(self, *, project_id: str, display_name: str | None = None, summary: str | None = None, tags: list[str] | None = None, actor_id: str | None = None, source_ref: str | None = None) -> SpineProject: ...
    def update_owner(self, *, project_id: str, owner_kind: str, owner_id: str | None = None, actor_id: str | None = None, source_ref: str | None = None) -> SpineProject: ...
    def transition_status(self, *, project_id: str, new_status: str, actor_id: str | None = None, reason: str | None = None, source_ref: str | None = None) -> SpineProject: ...
    def archive_project(self, *, project_id: str, actor_id: str | None = None, reason: str | None = None, force: bool = False, source_ref: str | None = None) -> SpineProject: ...
    def cancel_project(self, *, project_id: str, actor_id: str | None = None, reason: str | None = None, force: bool = False, source_ref: str | None = None) -> SpineProject: ...
    def reopen_project(self, *, project_id: str, actor_id: str | None = None, reason: str | None = None, source_ref: str | None = None) -> SpineProject: ...
    def attach_task(self, *, project_id: str, task_id: str, actor_id: str | None = None, source_ref: str | None = None) -> dict[str, Any]: ...
    def detach_task(self, *, project_id: str, task_id: str, actor_id: str | None = None, source_ref: str | None = None) -> dict[str, Any]: ...


@runtime_checkable
class ApprovalAdapter(Protocol):
    def find_target_task(self, *, room_id: str | None, tool_name: str, event_type: str) -> SpineTask | None: ...
    def mirror_approval_state(self, *, confirm_id: str, tool_name: str, state: str, payload: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def expire_pending(self, *, confirm_id: str) -> bool: ...


@runtime_checkable
class MemoryAdapter(Protocol):
    def emit_memory_signal(self, *, room_id: str, source_ref: str, signal_text: str, reopen_task_id: str | None = None, session: Any | None = None) -> dict[str, Any]: ...
    def validate_memory_redaction(self, *, payload: dict[str, Any]) -> dict[str, Any]: ...


@runtime_checkable
class MeetingAdapter(Protocol):
    def capture_meeting_artifact(self, *, artifact: Any, session: Any) -> dict[str, Any]: ...
    def emit_meeting_output(self, *, room_id: str, actor_id: str | None, artifact_type: str, artifact_id: str, content_markdown: str, session: Any | None = None) -> dict[str, Any]: ...


@runtime_checkable
class SecurityEventAdapter(Protocol):
    def emit_breakglass(self, *, room_id: str, user_id: str, event_type: str, confirm_id: str | None = None, payload: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def redact_security_payload(self, *, payload: dict[str, Any]) -> dict[str, Any]: ...


@runtime_checkable
class DashboardAdapter(Protocol):
    def get_room_overview(self, *, room_id: str) -> SpineDashboardSnapshot: ...
    def get_operator_queue(self, *, queue_name: str, limit: int = 25) -> list[SpineTask]: ...
    def get_task_detail(self, *, task_id: str) -> dict[str, Any]: ...
    def get_project_workload(self, *, room_id: str | None = None) -> dict[str, Any]: ...
